---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-eks
  region: us-east-1
fargateProfiles:
  - name: frontend-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: frontend-fargate
